[rewrite_local]
^https:\/\/api\.getmoshi\.app\/api\/v1\/licenses\/(?:me|activate|[^\/]+\/devices)(?:[\/?#]|$) url script-analyze-echo-response https://raw.githubusercontent.com/Yu9191/Rewrite/refs/heads/main/moshi/moshi-pro.js

[mitm]
hostname = api.getmoshi.app
